### ISSUE TITLE
samd_xtend: make -j1 fails because pins.h is not found

### ISSUE THREAD

**Issue by ricksorensen** [robert-hh/micropython#10] opened 2022-06-18 01:25 UTC
I am not sure how to report this- so am leaving a note here.  All the work you put into the SAMD21/51 extensions is great.   I am working with a SAMD21 (XIAO) for some small projects and appreciate the I2C and UART particularly.  However, I found a build issue which I think is in the make organization - with dependency definitions possibly.

If I initiate the micropython build (mpy_cross, submodules)  and then go to the to ports/samd directory:

` make -j4 BOARD=SEEED_XIAO` works great, as does `make -j2 BOARD=SEEED_XIAO`.  However make with a single process fails:

```
make -j1 BOARD=SEEED_XIAO`

make: Entering directory '/work/domicropy/micropython-builder/micropython/ports/samd'
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
GEN build-SEEED_XIAO/genhdr/qstr.i.last
machine_led.c:33:10: fatal error: pins.h: No such file or directory
   33 | #include "pins.h"
      |          ^~~~~~~~
compilation terminated.
machine_pin.c:37:10: fatal error: pins.h: No such file or directory
   37 | #include "pins.h"
      |          ^~~~~~~~
compilation terminated.
modsamd.c:33:10: fatal error: pins.h: No such file or directory
   33 | #include "pins.h"
      |          ^~~~~~~~
ED_XIAO
works great.  As does make -j2.  However, make -j1 fails
    make -j1 BOARD=SEEED_XIAO
````
Unfortunately my skills with make are a bit dated, and I am unfamiliar with the organization of make file includes for this project so I can't figure out a reasonable patch.  I tried moving files in the SRC parameter with little luck.

Thanks again -

Rick Sorensen

**Comment by robert-hh** [comment] 2022-06-23 20:08
Thanks Rick for the hint. pins.h is a generated file. So there must be something missing in the dependencies. The SEEED XIAO is a nice board. I assume, you also have seen the PR with the documentation.
I'm happy about any messages about errors.

**Comment by robert-hh** [comment] 2022-06-23 20:37
So the issue is fixed by changing Makefile. Thanks again for bringing it up.

**Closed as completed by robert-hh** 2022-06-23 20:37 UTC
Labels: bug
